


name: $(Date:yyyyMMdd)$(Rev:.r)-psfiddle

resources:
  repositories: 
  - repository: PSFiddle
    endpoint: hecflores
    type: github
    name: hecflores/PSFiddle
    
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/pkgs/nuget/NetCore/PSFiddle
   
stages:
  - stage: Build 
    displayName: Build PSFiddle
    jobs:  
    - job: Build
      displayName: Build PSFiddle
      pool:
        vmImage: 'windows-latest'
      steps:
        - script: dotnet restore
          displayName: Restore PSFiddle
          workingDirectory: src/pkgs/nuget/NetCore/PSFiddle
        - script: dotnet build
          displayName: Build PSFiddle
          workingDirectory: src/pkgs/nuget/NetCore/PSFiddle
        - script: dotnet pack -p:PackageVersion=2.1.0 -o src/pkgs/nuget/NetCore/PSFiddle
          displayName: Pack PSFiddle
          workingDirectory: src/pkgs/nuget/NetCore/PSFiddle
        - script: dotnet nuget push *.nupkg -k oy2lrq4gn6ipf4zpxyjqxdgux6j7ld3e3fvovn2rpqdsxy
          displayName: Push PSFiddle
          workingDirectory: src/pkgs/nuget/NetCore/PSFiddle
          
          