//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSFiddle.UIAutomation.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSFiddle.UIAutomation.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FileName NVARCHAR(200)
        ///DECLARE @OrganizationKey BIGINT
        ///DECLARE @UserEmail NVARCHAR(200)
        ///DECLARE @UserKey BIGINT
        ///DECLARE @AuditDetailsTypeKey INT
        ///DECLARE @Purchasing BIT
        ///DECLARE @Linking BIT
        ///
        ///SET @UserKey         = &apos;$(UserKey)&apos;
        ///SET @FileName        = &apos;$(FileName)&apos;
        ///SET @UserEmail       = &apos;$(UserEmail)&apos;
        ///SET @OrganizationKey = &apos;$(OrganizationKey)&apos;
        ///SET @Purchasing      = &apos;$(Purchasing)&apos;
        ///SET @Linking         = &apos;$(Linking)&apos;
        ///
        ///-- Parameter Values -- 
        ///SELECT @AuditDetailsTypeKey        = Para [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ComplianceMappingDataPopulation {
            get {
                return ResourceManager.GetString("ComplianceMappingDataPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their where some error validations when expecting none.
        /// </summary>
        public static string CounterpartyPage_ErrorValidationsExistedBuNotExpected {
            get {
                return ResourceManager.GetString("CounterpartyPage_ErrorValidationsExistedBuNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info! Please press upload to proceed..
        /// </summary>
        public static string CounterpartyPage_ValidationMessageForPleaseUploadToProceed {
            get {
                return ResourceManager.GetString("CounterpartyPage_ValidationMessageForPleaseUploadToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE_MERCHANT.
        /// </summary>
        public static string DeleteOperation_Approve {
            get {
                return ResourceManager.GetString("DeleteOperation_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_MERCHANT.
        /// </summary>
        public static string DeleteOperation_Update {
            get {
                return ResourceManager.GetString("DeleteOperation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string DetailsOfRelated {
            get {
                return ResourceManager.GetString("DetailsOfRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string DetailsOfSelf {
            get {
                return ResourceManager.GetString("DetailsOfSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string DetailsOfUser {
            get {
                return ResourceManager.GetString("DetailsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument was found as null.
        /// </summary>
        public static string Error_ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save to DB.
        /// </summary>
        public static string Error_Db_Save {
            get {
                return ResourceManager.GetString("Error_Db_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: One or more required arguments is null or empty.
        /// </summary>
        public static string Error_Null_Parameters {
            get {
                return ResourceManager.GetString("Error_Null_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AlphaID.
        /// </summary>
        public static string FinInst_Get_ParameterName {
            get {
                return ResourceManager.GetString("FinInst_Get_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SelectFinancialInstitutionOnAlphaID.
        /// </summary>
        public static string FinInst_Get_StoredProcName {
            get {
                return ResourceManager.GetString("FinInst_Get_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FinancialInstitutionKey.
        /// </summary>
        public static string FinInst_GetById_ParameterName {
            get {
                return ResourceManager.GetString("FinInst_GetById_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SelectFinancialInstitution.
        /// </summary>
        public static string FinInst_GetById_StoredProcName {
            get {
                return ResourceManager.GetString("FinInst_GetById_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FinancialInstitutionType.
        /// </summary>
        public static string FinInst_Update_ParameterName {
            get {
                return ResourceManager.GetString("FinInst_Update_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_InsertUpdateFinancialInstitution.
        /// </summary>
        public static string FinInst_Update_StoredProcName {
            get {
                return ResourceManager.GetString("FinInst_Update_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OrgKey.
        /// </summary>
        public static string FinInstOrg_DeleteValidation_ParameterName {
            get {
                return ResourceManager.GetString("FinInstOrg_DeleteValidation_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_ValidateCardOrMerchandIdForDeletion.
        /// </summary>
        public static string FinInstOrg_DeleteValidation_StoredProcName {
            get {
                return ResourceManager.GetString("FinInstOrg_DeleteValidation_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FinInstOrgKey.
        /// </summary>
        public static string FinInstOrg_Get_ParameterName {
            get {
                return ResourceManager.GetString("FinInstOrg_Get_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SelectFinancialInstitutionOrganization.
        /// </summary>
        public static string FinInstOrg_Get_StoredProcName {
            get {
                return ResourceManager.GetString("FinInstOrg_Get_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_UpdateFinanicalInstutionDefaults.
        /// </summary>
        public static string FinInstOrg_Update_Defaults {
            get {
                return ResourceManager.GetString("FinInstOrg_Update_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FinancialInstitutionOrganizationType.
        /// </summary>
        public static string FinInstOrg_Update_ParameterName {
            get {
                return ResourceManager.GetString("FinInstOrg_Update_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_InsertUpdateFinancialInstitutionOrganization.
        /// </summary>
        public static string FinInstOrg_Update_StoredProcName {
            get {
                return ResourceManager.GetString("FinInstOrg_Update_StoredProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FileName NVARCHAR(200) = &apos;$(FileName)&apos; -- Provide new file name if you want to create data for new file
        ///DECLARE @UserEmail NVARCHAR(200) = &apos;$(UserEmail)&apos;
        ///DECLARE @UserKey BIGINT
        ///SET @UserKey = &apos;$(UserKey)&apos;
        ///
        ///-- Declarations -- 
        ///DECLARE @OrganizationEventHistoryType [dbo].[OrganizationEventHistoryType]
        ///DECLARE @MatchingAlgorithmTypeKey     BIGINT
        ///DECLARE @CorrelationID                NVARCHAR(100)
        ///DECLARE @AuditDetailsTypeKey          INT
        ///DECLARE @MatchingProcessCompleteKey   INT
        ///DECLARE @ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MatchingMock {
            get {
                return ResourceManager.GetString("MatchingMock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Mpgs_Error_Response {
            get {
                return ResourceManager.GetString("Mpgs_Error_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string Mpgs_Success_Response {
            get {
                return ResourceManager.GetString("Mpgs_Success_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apiOperation.
        /// </summary>
        public static string ParameterName_ApiOperation {
            get {
                return ResourceManager.GetString("ParameterName_ApiOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.address.city.
        /// </summary>
        public static string ParameterName_Merchant_Address_City {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.address.countryCode.
        /// </summary>
        public static string ParameterName_Merchant_Address_Country {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.address.state.
        /// </summary>
        public static string ParameterName_Merchant_Address_State {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Address_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.address.street1.
        /// </summary>
        public static string ParameterName_Merchant_Address_Street1 {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Address_Street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.address.postcode.
        /// </summary>
        public static string ParameterName_Merchant_Address_Zip {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Address_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.categoryCode.
        /// </summary>
        public static string ParameterName_Merchant_CategoryCode {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.goodsDescription.
        /// </summary>
        public static string ParameterName_Merchant_GoodsDescription {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_GoodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.locale.
        /// </summary>
        public static string ParameterName_Merchant_Locale {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.name.
        /// </summary>
        public static string ParameterName_Merchant_Name {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.state.
        /// </summary>
        public static string ParameterName_Merchant_State {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchant.timeZone.
        /// </summary>
        public static string ParameterName_Merchant_Timezone {
            get {
                return ResourceManager.GetString("ParameterName_Merchant_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5999.
        /// </summary>
        public static string ParameterValue_Merchant_CategoryCode {
            get {
                return ResourceManager.GetString("ParameterValue_Merchant_CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISCELLANEOUS.
        /// </summary>
        public static string ParameterValue_Merchant_GoodsDescription {
            get {
                return ResourceManager.GetString("ParameterValue_Merchant_GoodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_US.
        /// </summary>
        public static string ParameterValue_Merchant_Locale {
            get {
                return ResourceManager.GetString("ParameterValue_Merchant_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        public static string ParameterValue_Merchant_State {
            get {
                return ResourceManager.GetString("ParameterValue_Merchant_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Singapore.
        /// </summary>
        public static string ParameterValue_Merchant_Timezone {
            get {
                return ResourceManager.GetString("ParameterValue_Merchant_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Business Name,Street Address,City,State/Province,Country,Zip,URL,Contact Name,Contact Email Address,TIN,Registration Number,VAT
        ///FARMSON SEEDS INDIA PRIVATE LIMITED (OPC),Address 123,Hyderabad,Telangana,India,588911,http://xyz.com,Random Guy,msak@ksa.com,78789,897894,8766
        ///PAX INTERNATIONAL TRADING OPC PRIVATE LIMITED,Address 124,Hyderabad1,Telangana1,India,588912,http://xyz.com,Random Guy1,msak1@ksa.com,78790,897895,8767
        ///SIGINTEGRITY SOLUTIONS PRIVATE LIMITED (OPC),Address 125,Hyderabad2,Telang [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleCounterpartyFile {
            get {
                return ResourceManager.GetString("SampleCounterpartyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Status_ApproveRequest {
            get {
                return ResourceManager.GetString("Status_ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Status_CancelRequest {
            get {
                return ResourceManager.GetString("Status_CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Status_DeleteRequest {
            get {
                return ResourceManager.GetString("Status_DeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_PendingAdd {
            get {
                return ResourceManager.GetString("Status_PendingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingDeleteApproval.
        /// </summary>
        public static string Status_PendingDeleteApproval {
            get {
                return ResourceManager.GetString("Status_PendingDeleteApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingDeletion.
        /// </summary>
        public static string Status_PendingDeletion {
            get {
                return ResourceManager.GetString("Status_PendingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Status_RejectRequest {
            get {
                return ResourceManager.GetString("Status_RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 385.
        /// </summary>
        public static string TriggerKey_SendAdminMPGSConfig {
            get {
                return ResourceManager.GetString("TriggerKey_SendAdminMPGSConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string TriggerKey_SendApprovalEmailForAccountAdd {
            get {
                return ResourceManager.GetString("TriggerKey_SendApprovalEmailForAccountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        public static string TriggerKey_SendApproveEmailForCardAddToApprover {
            get {
                return ResourceManager.GetString("TriggerKey_SendApproveEmailForCardAddToApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 425.
        /// </summary>
        public static string TriggerKey_SendDeleteApprovedNotificationToApprover_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteApprovedNotificationToApprover_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 430.
        /// </summary>
        public static string TriggerKey_SendDeleteApprovedNotificationToApprover_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteApprovedNotificationToApprover_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 415.
        /// </summary>
        public static string TriggerKey_SendDeleteApprovedNotificationToInitiator_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteApprovedNotificationToInitiator_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 420.
        /// </summary>
        public static string TriggerKey_SendDeleteApprovedNotificationToInitiator_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteApprovedNotificationToInitiator_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 470.
        /// </summary>
        public static string TriggerKey_SendDeleteCancelledNotificationToApprover_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteCancelledNotificationToApprover_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 475.
        /// </summary>
        public static string TriggerKey_SendDeleteCancelledNotificationToApprover_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteCancelledNotificationToApprover_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 460.
        /// </summary>
        public static string TriggerKey_SendDeleteCancelledNotificationToDataManager_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteCancelledNotificationToDataManager_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 465.
        /// </summary>
        public static string TriggerKey_SendDeleteCancelledNotificationToDataManager_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteCancelledNotificationToDataManager_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 455.
        /// </summary>
        public static string TriggerKey_SendDeleteFailureNotificationToIT {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteFailureNotificationToIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 405.
        /// </summary>
        public static string TriggerKey_SendDeleteNotificationToApprover_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteNotificationToApprover_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 410.
        /// </summary>
        public static string TriggerKey_SendDeleteNotificationToApprover_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteNotificationToApprover_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 395.
        /// </summary>
        public static string TriggerKey_SendDeleteNotificationToIntiator_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteNotificationToIntiator_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string TriggerKey_SendDeleteNotificationToIntiator_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteNotificationToIntiator_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 445.
        /// </summary>
        public static string TriggerKey_SendDeleteRejectedNotificationToApprover_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteRejectedNotificationToApprover_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string TriggerKey_SendDeleteRejectedNotificationToApprover_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteRejectedNotificationToApprover_MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 435.
        /// </summary>
        public static string TriggerKey_SendDeleteRejectedNotificationToInitiator_Card {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteRejectedNotificationToInitiator_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 440.
        /// </summary>
        public static string TriggerKey_SendDeleteRejectedNotificationToInitiator_MerchantId {
            get {
                return ResourceManager.GetString("TriggerKey_SendDeleteRejectedNotificationToInitiator_MerchantId", resourceCulture);
            }
        }
    }
}
