
name: PSFiddle.Common.$(Rev:r)

resources:
  repositories: 
  - repository: PSFiddle
    type: github 
    name: hecflores/PSFiddle
 
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/pkgs/powershellgallery/powershell/*
    - cli/templates/base.yml
    

variables:
- template: /cli/templates/base-variables.yml

jobs:
- template: /cli/templates/base.yml  # Template reference
  parameters:
    type: NuGetPackage
    metadata:
      packageName: PSFiddle.Common
          
    


    
   