

name: $(Date:yyyyMMdd)$(Rev:r)

resources:
  repositories: 
  - repository: PSFiddle
    type: github
    name: hecflores/PSFiddle
    
trigger:
  branches:
    include:
    - master
   
stages:
  - stage: Build 
    displayName: Build 
    jobs:  
       - job: Build
         displayName: Build 
         pool:
            vmImage: 'ubuntu-latest'
         steps:
            script: echo "Hector"
       
       
    
   